CREATE TABLE "user"
(
    id            bigint generated by default as identity primary key,
    role          varchar(100) not null,
    login         varchar(100) not null,
    password      varchar(255) not null,
    mail          varchar(255)
);

CREATE INDEX ix_login ON "user" (login);

CREATE TABLE user_token
(
    id         bigint generated by default as identity primary key,
    token      uuid not null,
    expires_at timestamp,
    user_id    bigint
        constraint fk_user references "user"
);

CREATE INDEX ix_token ON user_token (token);

