CREATE TABLE user_token
(
    id         bigint generated by default as identity primary key,
    token      uuid not null,
    expires_at timestamp
);

CREATE INDEX ix_token ON user_token (
     token
    );

CREATE TABLE "user" (
  id            bigint generated by default as identity primary key,
  role          varchar(100) not null,
  login         varchar(100) not null,
  password      varchar(255) not null,
  user_token_id bigint constraint fk_user_token references user_token
);

